const checklistItems=["Permis de conduire","Carte d’assurance","Téléphone chargé","Sena connecté","CarPlay connecté","Casque","Gants","Manteau","Bottes","Lunettes","Essence","Pression des pneus","Aucun voyant allumé","Coffres fermés","Eau ou collation"];
const challengeItems=["Première sortie seule","Premier plein","Premier 100 km","Premier pont","Première autoroute","Première ride de groupe","Ride de Filles","5 000 km","10 000 km"];
const load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const state={rides:load("v3Rides",[]),routes:load("v3Routes",[]),maintenance:load("v3Maintenance",{mileage:0,next:0,fuel:78,notes:""}),challenges:load("v3Challenges",{})};
const save=()=>{localStorage.setItem("v3Rides",JSON.stringify(state.rides));localStorage.setItem("v3Routes",JSON.stringify(state.routes));localStorage.setItem("v3Maintenance",JSON.stringify(state.maintenance));localStorage.setItem("v3Challenges",JSON.stringify(state.challenges));};
function go(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===id));scrollTo({top:0,behavior:"smooth"});renderAll();}
document.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)go(b.dataset.page);});
function greeting(){const h=new Date().getHours();return h<12?"☀ Bonjour Émilie !":h<18?"🌤 Bon après-midi Émilie !":"🌙 Bonne soirée Émilie !";}
function dateFr(d){return new Date(d+"T12:00:00").toLocaleDateString("fr-CA",{day:"numeric",month:"long",year:"numeric"});}
function renderChecklist(){const box=document.getElementById("checklistItems");box.innerHTML="";checklistItems.forEach((x,i)=>{const l=document.createElement("label");l.className="check";l.innerHTML=`<input type="checkbox" data-check="${i}"><span>${x}</span>`;box.appendChild(l)});box.querySelectorAll("input").forEach(i=>i.onchange=updateChecklist);updateChecklist();}
function updateChecklist(){const a=[...document.querySelectorAll("[data-check]")],n=a.filter(x=>x.checked).length;document.getElementById("checkCount").textContent=`${n} / ${a.length}`;document.getElementById("progressFill").style.width=`${n/a.length*100}%`;document.getElementById("readyBtn").disabled=n!==a.length;}
document.getElementById("resetChecklist").onclick=()=>{document.querySelectorAll("[data-check]").forEach(x=>x.checked=false);updateChecklist();};
document.getElementById("readyBtn").onclick=()=>alert("Tout est prêt. Bonne route Émilie ! 💙");
document.getElementById("rideForm").onsubmit=e=>{e.preventDefault();state.rides.unshift(Object.fromEntries(new FormData(e.target).entries()));save();e.target.reset();go("journal");};
document.getElementById("routeForm").onsubmit=e=>{e.preventDefault();state.routes.unshift(Object.fromEntries(new FormData(e.target).entries()));save();e.target.reset();renderRoutes();};
document.getElementById("maintenanceForm").onsubmit=e=>{e.preventDefault();state.maintenance={mileage:+mileageInput.value||0,next:+maintenanceInput.value||0,fuel:+fuelInput.value||0,notes:maintenanceNotes.value};save();renderMaintenance();};
function renderRides(){const list=document.getElementById("rideList");list.innerHTML=state.rides.length?"":"<div class='card'>Ta prochaine aventure apparaîtra ici. 💙</div>";state.rides.forEach((r,i)=>{const a=document.createElement("article");a.className="card";a.innerHTML=`<div class="card-top"><h3>${r.name}</h3><button class="delete" data-r="${i}">Supprimer</button></div><p>${dateFr(r.date)} · ${r.distance||0} km ${r.duration?`· ${r.duration}`:""}</p><p>${r.weather||""}</p><p>Plaisir ${r.fun}/10 · Confiance ${r.confidence}/10</p>${r.favorite?`<p>Moment préféré : ${r.favorite}</p>`:""}${r.notes?`<p>${r.notes}</p>`:""}`;list.appendChild(a)});const km=state.rides.reduce((s,r)=>s+(+r.distance||0),0);const conf=state.rides.length?state.rides.reduce((s,r)=>s+(+r.confidence||0),0)/state.rides.length:0;const longest=Math.max(0,...state.rides.map(r=>+r.distance||0));journalCount.textContent=seasonRides.textContent=statsRides.textContent=state.rides.length;journalKm.textContent=`${km} km`;journalConfidence.textContent=statsConfidence.textContent=state.rides.length?`${conf.toFixed(1)}/10`:"—";seasonKm.textContent=statsKm.textContent=km;longestRide.textContent=statsLongest.textContent=`${longest} km`;if(state.rides.length){const r=state.rides[0];lastRideDate.textContent=dateFr(r.date);lastRideInfo.textContent=`${r.distance||0} km${r.duration?` · ${r.duration}`:""}${r.weather?` · ${r.weather}`:""}`;lastRideName.textContent=r.name;}else{lastRideDate.textContent="Aucune";lastRideInfo.textContent="Ajoute ta première sortie";lastRideName.textContent="—";}}
document.addEventListener("click",e=>{const b=e.target.closest("[data-r]");if(b&&confirm("Supprimer cette sortie ?")){state.rides.splice(+b.dataset.r,1);save();renderRides();}const c=e.target.closest("[data-route]");if(c&&confirm("Supprimer ce parcours ?")){state.routes.splice(+c.dataset.route,1);save();renderRoutes();}});
function renderRoutes(){routeList.innerHTML=state.routes.length?"":"<div class='card'>Ajoute ici les routes que tu aimerais refaire.</div>";state.routes.forEach((r,i)=>{const a=document.createElement("article");a.className="card";a.innerHTML=`<div class="card-top"><h3>${r.name}</h3><button class="delete" data-route="${i}">Supprimer</button></div><p>${r.distance||0} km · ${r.difficulty}</p>`;routeList.appendChild(a)});routeCount.textContent=state.routes.length;}
function renderMaintenance(){const m=state.maintenance;mileageInput.value=m.mileage||"";maintenanceInput.value=m.next||"";fuelInput.value=m.fuel??78;maintenanceNotes.value=m.notes||"";vehicleKm.textContent=`${m.mileage||0} km`;fuelValue.textContent=`${m.fuel??78}%`;fuelMessage.textContent=m.fuel>=60?"Bien parti !":m.fuel>=30?"À surveiller":"Pense à faire le plein";if(!m.next){maintenanceStatus.innerHTML="<strong>Prochain entretien à définir</strong><p>Ajoute le kilométrage prévu.</p>";maintenanceDue.textContent="À définir";maintenanceSub.textContent="Ajoute ton prochain kilométrage";}else{const r=m.next-m.mileage;if(r>0){maintenanceStatus.innerHTML=`<strong>Entretien à ${m.next} km</strong><p>Il reste environ ${r} km.</p>`;maintenanceDue.textContent=`Dans ${r} km`;maintenanceSub.textContent=`À ${m.next} km`;}else{maintenanceStatus.innerHTML="<strong>Entretien à prévoir</strong><p>Le kilométrage prévu est atteint.</p>";maintenanceDue.textContent="Maintenant";maintenanceSub.textContent="Le kilométrage est atteint";}}}
function renderChallenges(){challengeList.innerHTML="";challengeItems.forEach((x,i)=>{const l=document.createElement("label");l.className="challenge";l.innerHTML=`<input type="checkbox" data-ch="${i}" ${state.challenges[i]?"checked":""}><span>${state.challenges[i]?"★":"☆"} ${x}</span>`;challengeList.appendChild(l)});challengeList.querySelectorAll("input").forEach(x=>x.onchange=e=>{state.challenges[e.target.dataset.ch]=e.target.checked;save();renderChallenges();});}
function renderAll(){greeting.textContent=greeting();today.textContent=new Date().toLocaleDateString("fr-CA",{weekday:"long",day:"numeric",month:"long",year:"numeric"});seasonYear.textContent=new Date().getFullYear();renderRides();renderRoutes();renderMaintenance();renderChallenges();}
document.querySelector('#rideForm [name="date"]').value=new Date().toISOString().slice(0,10);
renderChecklist();renderAll();
